service: todos-service


plugins:
  - serverless-localstack
  - serverless-python-requirements


custom:
  localstack:
    stages:
      - local
#    debug: true

  pythonRequirements:
    dockerizePip: false
    useDownloadCache: false
    useStaticCache: false
    slim: true


package:
  individually: true
  patterns:
    - "!todos/__pycache__"
    - "!node_modules"
    - "!.idea"
    - "!.pre-commit-config.yaml"
    - "!package-lock.json"
    - "!postman_collection.json"


provider:
  name: aws
  region: us-east-1
  runtime: python3.8
  environment:
    DYNAMODB_TABLE: ${self:service}-${opt:stage, self:provider.stage}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}"


functions:
  create:
    handler: todos/create.handler
    events:
      - http:
          path: todos
          method: post
          cors: true

  list:
    handler: todos/list.handler
    events:
      - http:
          path: todos
          method: get
          cors: true

  read:
    handler: todos/read.handler
    events:
      - http:
          path: todos/{id}
          method: get
          cors: true

  update:
    handler: todos/update.handler
    events:
      - http:
          path: todos/{id}
          method: put
          cors: true

  delete:
    handler: todos/delete.handler
    events:
      - http:
          path: todos/{id}
          method: delete
          cors: true


resources:
  Resources:
    myTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.DYNAMODB_TABLE}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
